# Generated by Django 4.2.9 on 2025-05-10 03:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo_estudiante',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='profesores',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='programa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materia',
            name='dia_clase',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], default='Lunes', max_length=10),
        ),
        migrations.AddField(
            model_name='materia',
            name='hora_fin',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='materia',
            name='hora_inicio',
            field=models.TimeField(default='07:00'),
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='academic.profesor'),
        ),
        migrations.AddField(
            model_name='materia',
            name='salon',
            field=models.CharField(default='Por asignar', max_length=50),
        ),
        migrations.AddField(
            model_name='nota',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='academic.materia'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academic.estudiante'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academic.materia'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.estudiante'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academic.evaluacion'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'evaluacion')},
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table=None,
        ),
        migrations.AlterModelTable(
            name='evaluacion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materia',
            table=None,
        ),
        migrations.AlterModelTable(
            name='matricula',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nota',
            table=None,
        ),
        migrations.RemoveField(
            model_name='nota',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='fecha_registro',
        ),
    ]
