# Generated by Django 4.2.9 on 2025-05-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_nota_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Aprobada', 'Aprobada'), ('Reprobada', 'Reprobada'), ('Retirada', 'Retirada')], default='Activa', max_length=20),
        ),
    ]
