# Generated by Django 4.2.9 on 2025-05-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_matricula_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='profesor',
        ),
        migrations.AddField(
            model_name='materia',
            name='profesores',
            field=models.ManyToManyField(related_name='materias_asignadas', through='academic.ProfesorMateria', to='academic.profesor'),
        ),
    ]
